services:
  artemis:
    image: apache/activemq-artemis:latest-alpine
    container_name: artemis
    ports:
      - "61616:61616" # amqp
      - "8161:8161"   # web console
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin

  postgres:
    image: postgres:17
    container_name: postgres17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alerthub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: