spring:
  application:
    name: alerthub
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USER:admin}
    password: ${ARTEMIS_PASSWORD:admin}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/alerthub}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
camel:
  dataformat:
    jackson:
      auto-discover-object-mapper: true